export let long_name_1 = ''
export let long_name_2 = ''
export let long_name_3 = ''
export let long_name_4 = ''
export let long_name_5 = ''

export type long_type_1 = ''
export type long_type_2 = ''
export type long_type_3 = ''
export type long_type_4 = ''
export type long_type_5 = ''
